### ISSUE TITLE
Mod generates, and looks for, invalid config file

### ISSUE THREAD

**Issue by Shahelion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10#2]
Using the newest version from Modrinth. The config is called "Matter Overdrive.cfg", however when launching with this version, it creates a file called "MatterOverdrive" with no .cfg file extension, and ignores the actual config file. I noticed this because it crashed from an ID conflict because it reverted to the old enchantment ID.

![image](https://github.com/Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10/assets/6917535/e8cf8f8e-735b-4cca-ab48-640f7f191d12)

**Comment by infiniteblock** [comment]
https://cdn.discordapp.com/attachments/1209064386950471700/1224159271004934184/MatterOverdrive-1.7.10-0.4.4.jar?ex=661c7a29&is=660a0529&hm=10c9fa14baad1a915cb32702d0037d2b819ed9898361f28f5abec879b827e97f&

try this have fixed it so config file is "Matter Overdrive.cfg"

**Comment by Shahelion** [comment]
Looks like it works now!
